---
title: "Udemy_R_Course1_Homework"
author: "Zhongyuelin"
date: "2022-10-12"
output: pdf_document
---
Homework 2 : Law of Large Numbers
```{r}
N=1000
counter=0
for (i in rnorm(N)) {
  if(i>-1 & i<1){
    counter=counter+1
  }
  
}
counter/N

```
Homework 3: Financial Statement Analysis
```{r}
revenue <- c(14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50)
expenses <- c(12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96)

#profit for each match
profit=revenue-expenses
profit
#profit after tax(tax rate is 30%)
tax= round(profit*0.3,digits=2)
tax
profit.after.tax=profit-tax
profit.after.tax
#profit margin for each month(profit after tax divided by revenue)
profit.margin=round(profit.after.tax/revenue,2)
#good month (where the profit.after.tax greater than mean for profit)
mean_pat=mean(profit.after.tax)
mean_pat
good.month=profit.after.tax>mean_pat
good.month
#Bad Month(PAT<mean_pat)
bad_month=profit.after.tax<mean_pat
bad_month
#Best month(the PAT max for the year)
best.month=profit.after.tax==max(profit.after.tax)
best.month
#Worth month(Min Pat for the year)
worst.month=profit.after.tax==min(profit.after.tax)
worst.month
#units of thousdands
revenue.1000=round(revenue/1000)
expenses.1000=round(expenses/1000)
profits.1000=round(profit/1000)
profit.after.tax.1000=round(profit.after.tax/1000)

```

